### PR TITLE
Debug setting for XMC4Arduino & change online help link

### PR DESCRIPTION
**Pull request by LinjingZhang**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Support debug in Arduino IDE2.x. (automatically select device and jlink, juhu!)
Change online help link and change the logic of release-json-file generation (Juan already reviewed this part :)

Related Issue
NA

Context
Debug function only tested with XMC4700 on windows. Anyone with native Linux please test it. It should work as well.

### CODE REVIEW

**Review by jaenrig-ifx — APPROVED** [review]
Are the other programmers required? atmel_ice, sam_ice? edgb? 👍

**Comment by LinjingZhang** [comment]
> Are the other programmers required? atmel_ice, sam_ice? edgb? 👍

you are right - the other programmers could be removed.

**Review by OlafFilies — APPROVED** [review]
I think the additional programmers are a left over from researching the debugging. They do not harm but should be removed.

**Comment by jaenrig-ifx** [comment]
Yep, then please remove them :)

**Comment by LinjingZhang** [comment]
I removed the unused programmers and merged. Thanks!

**Pull request merged**
