### PR TITLE
Create new serial config file

### PR DESCRIPTION
**Pull request by danielstuart14**
This commit separates the serial configuration from pins_arduino.
This is done so pins_arduino can be included earlier on Arduino.h,
and by doing that, Serial1 is fixed on supported boards.

### CODE REVIEW

**Comment by techpaul** [comment]
Does this actually work???
Have you tested it as I do not see  this helps.

I suspect the problem is actually something a LOT SIMPLER please check #23 as that has an implementation that was done for XMC1100 XMC2GO for 2 serial and a test sketch I suggest you use to test your fixes.

I suspect the problem is simply the last line of following
~~~
XMC_UART_t XMC_UART_0 =
  {
  .channel              = XMC_UART0_CH0,
  .rx                   = { .port = (XMC_GPIO_PORT_t*)PORT1_BASE,
                            .pin  = (uint8_t)4
                          },
  .rx_config            = { .mode = XMC_GPIO_MODE_INPUT_TRISTATE,
                            .output_level     = XMC_GPIO_OUTPUT_LEVEL_HIGH,
                            .output_strength  = XMC_GPIO_OUTPUT_STRENGTH_STRONG_SOFT_EDGE
                          },
  .tx                   = { .port = (XMC_GPIO_PORT_t*)PORT1_BASE,
                            .pin  = (uint8_t)5
                          },
  .tx_config            = { .mode = (XMC_GPIO_MODE_t) XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT2,
                            .output_level     = XMC_GPIO_OUTPUT_LEVEL_HIGH,
                            .output_strength  = XMC_GPIO_OUTPUT_STRENGTH_STRONG_SOFT_EDGE
                          },
  .input_source_dx0     = (XMC_USIC_INPUT_t)USIC0_C0_DX0_P1_4,
  .input_source_dx1     = XMC_INPUT_INVALID,
  .input_source_dx2     = XMC_INPUT_INVALID,
  .input_source_dx3     = XMC_INPUT_INVALID,
  .irq_num              = USIC0_0_IRQn,
  .irq_service_request  = 0
  };

XMC_UART_t XMC_UART_1 =
  {
  .channel              = XMC_UART1_CH0,
  .rx                   = { .port = (XMC_GPIO_PORT_t*)PORT2_BASE,
                            .pin  = (uint8_t)15
                          },
  .rx_config            = { .mode = XMC_GPIO_MODE_INPUT_TRISTATE,
                            .output_level     = XMC_GPIO_OUTPUT_LEVEL_HIGH,
                            .output_strength  = XMC_GPIO_OUTPUT_STRENGTH_STRONG_SOFT_EDGE
                          },
  .tx                   = { .port = (XMC_GPIO_PORT_t*)PORT2_BASE,
                            .pin  = (uint8_t)14
                          },
  .tx_config            = { .mode = (XMC_GPIO_MODE_t) XMC_GPIO_MODE_OUTPUT_PUSH_PULL_ALT2,
                            .output_level     = XMC_GPIO_OUTPUT_LEVEL_HIGH,
                            .output_strength  = XMC_GPIO_OUTPUT_STRENGTH_STRONG_SOFT_EDGE
                          },
  .input_source_dx0     = (XMC_USIC_INPUT_t)USIC1_C0_DX0_P2_15,
  .input_source_dx1     = XMC_INPUT_INVALID,
  .input_source_dx2     = XMC_INPUT_INVALID,
  .input_source_dx3     = XMC_INPUT_INVALID,
  .irq_num              = USIC1_0_IRQn,
  .irq_service_request  = 0
   };
~~~
I suspect the second port's  definition of irq_service_request should be 1 as in
~~~
  .irq_service_request  = 1
~~~

**Comment by danielstuart14** [comment]
Yes it does, "HardwareSerial.h" checks NUM_SERIAL for the amount of serial ports available, but, as seeing on "Android.h", the "pins_arduino.h" is only included after "HardwareSerial.h".
This way, even on xmc4700 relax kit (which has NUM_SERIAL = 2), the second serial was never enabled/defined, see this line: https://github.com/Infineon/XMC-for-Arduino/blob/0fa47ed19a65ace89f021b51b33c64ef414607cb/arm/cores/HardwareSerial.h#L130
That's what I was talking about when saying that NUM_SERIAL wasn't defined.

This commit only separates pins_arduino into two files because all the serial related definitions need to be done after the include of "HardwareSerial.h", but, without defining NUM_SERIAL before "HardwareSerial.h" include the second serial would never work.

Also, this commit doesn't add/remove any serial interface. It just make the secondary serial to work on boards that already have it enabled.

You can check it on boards with two Serials (Ex: xmc4700 relax kit), before this commit, Serial1 wasn't even declared.

**Comment by techpaul** [comment]
I have delved into the core files and there are a series of issues and I think simpler solutions

1.  HardwareSerial.h and .cpp are NOT board agnostic by use of NUM_SERIAL
2.  HardwareSerial.cpp includes HardwareSerial.h which early on includes Arduino.h which again includes HardwareSerial.h all before pins_arduino.h

Suggested and more maintainable solution

- Move board specific irq handlers event handlers and extern definitions to pins_arduino.h for each variation in different sections for ARDUINO_MAIN and always sections
- Change HardwareSerial.cpp to include Arduino.h which will include HardwareSerial.h
- Remove include Arduino.h from HardwareSerial.h 

With SOME of the above done and doing the following at end of XMC4700 Relax Kit/pins_arduino.h before last #endif
~~~
#ifdef __cplusplus
extern HardwareSerial Serial;
extern HardwareSerial Serial1;
#endif
~~~

Solved the definition problem for me

**Comment by techpaul** [comment]
Some of this issue is probably the build operation not using cpp build instructions for a .ino file

@mhollfelder Probably want to check your latest build mods 

I will sort out a simpler set of fixes making HardwareSerial less board specific as classes should be

**Comment by AlucardMode0** [comment]
> I have delved into the core files and there are a series of issues and I think simpler solutions
> 
> 1. HardwareSerial.h and .cpp are NOT board agnostic by use of NUM_SERIAL
> 2. HardwareSerial.cpp includes HardwareSerial.h which early on includes Arduino.h which again includes HardwareSerial.h all before pins_arduino.h
> 
> Suggested and more maintainable solution
> 
> * Move board specific irq handlers event handlers and extern definitions to pins_arduino.h for each variation in different sections for ARDUINO_MAIN and always sections
> * Change HardwareSerial.cpp to include Arduino.h which will include HardwareSerial.h
> * Remove include Arduino.h from HardwareSerial.h
> 
> With SOME of the above done and doing the following at end of XMC4700 Relax Kit/pins_arduino.h before last #endif
> 
> ```
> #ifdef __cplusplus
> extern HardwareSerial Serial;
> extern HardwareSerial Serial1;
> #endif
> ```
> 
> Solved the definition problem for me

soo what should i do to make Serial1 work ?

**Comment by techpaul** [comment]
Use the develop branch for now until a new version is released, as that incorporates fixes detailed above and in the merged files to ensure these things happen correctly.

See pull request #126

**Pull request closed without merging**
