### PR TITLE
Updates for XMC Radar Baseband board XMC4700 - Pulsed doppler 

### PR DESCRIPTION
**Pull request by mkiessling-ifx**
to sync with RDK 1.5.1

### CODE REVIEW

**Comment by mhollfelder** [comment]
Rebased pull request to `develop` branch.

**Comment by mkiessling-ifx** [comment]
Sure, o.k. thank you!
Michael

**Comment by techpaul** [comment]
A few issues

Firstly boards.txt and platform.txt have not been updated to change the board name

Secondly changes to board name not always the same in readme.md
At least lines 94 and 142 say

~~~
Radar Baseboard XMC4700
~~~
Should say
~~~
XMC4700 Radar Baseboard
~~~

Thirdly most of the screenshot images in readme.md now need updating to show new
object name and new board name

**Comment by techpaul** [comment]
Also many pages on the Wiki need to reflect this board name change
At least 
1.  Board page
2.  Menu to access it
3.  Home page link(s)

**Comment by mkiessling-ifx** [comment]
Hi Paul,

thank you for the hint of the naming, Well it was there before, I will update it.

But unfortunately  even the Wiki-link is then wrong, do we change it?
Line 3 and Line 172: https://github.com/Infineon/XMC-for-Arduino/wiki/Radar-Baseboard-XMC4700
It seems to be only a redirect.

I changed boards.txt, but I do not what you mean w.r.t. platform.txt. I did not find something special here.

Maybe also the links that are referred to in the readme.md needs to be changed in wiki.

While looking through the code I also found something that is not clear to me:


1)      e.g. in several pins_arduino.h the define XMC_BOARD is defined, but with spaces, like “#define XMC_BOARD           XMC 4700 Relax Kit”


2)      then analogwritetest.ino: the define is used like: #if XMC_BOARD == XMC4700_Relax_Kit …  (with underscore)



3)      further in IFX9201 examples another define “XMC_BOARD_NAME” is used

#ifdef XMC_BOARD_NAME
Serial.print( "Running on - " );
str1( XMC_BOARD_NAME );
#endif

4)      in ..\arm\libraries\DeviceControlXMC\examples\DieTemperatureMeasurement\DieTemperatureMeasurement.ino  only “XMC_BOARD” …
Serial.print( "Running on " );
str2( XMC_BOARD );

is used


è I suggest to use it like

#define XMC_BOARD_NAME   “XMC 4700 Relax Kit”

#define XMC_BOARD                   XMC_4700_RELAX_KIT
                To get it consistent and update for all boards.

I changed the variant for XMC4700 Radar Board accordingly already.

I will raise pull request.

Thank you
Michael

**Comment by techpaul** [comment]
Yes you will probably need to rename (change title and references to) several pages

XMC_BOARD and XMC_BOARD_NAME seems to be a hangover from an old bug with things getting confused by compiler -D options.

Putting what is define into "name" only means those " " get printed as WELL as 'name', basically you want a sensible string to display or be prepended or appended by other outputs

The main issue is you must use XMC 4700 (with a space) not XMC4700 as this will conflict with compiler flags -DXMC4700 so any board name becomes displayed or evaluated as a value of 1, all naming has gone.

I will check through the examples and tests to make sure things are consistent as they should all be XMC_BOARD and the device must be XMC<SPACE>number to be readable and not conflict

**Pull request merged**
