### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tinymanta**
small update on README.md

By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Provide the information we need to review your PR. What problem does the pull request solve? "Bug fix" is not a good description.

Related Issue
If you opened an issue before creating the PR, point to it here.

Context
What do we need to know about your development environment, tools, target, and so on. Screenshots are always helpful if there is a UI element to this PR.

### CODE REVIEW

**Review by jaenrig-ifx — APPROVED** [review]

**Comment by techpaul** [comment]
This will need more changes than Readme.md as changing a board name requires changes to Wiki and boards.txt for starters.

As it stands you have changed a board name in one place and nothing else matches

**Review by jaenrig-ifx — CHANGES_REQUESTED** [review]
Yup, I went to fast. Didn´t see the last part modification.
Thanks @techpaul.

**Comment by techpaul** [comment]
Looking at Readme.md there are a couple of mentions of Radar board only one is changed and one points to Radar wiki page.

**Comment by tinymanta** [comment]
This PR was just to confirm my current setup... will do a 2nd with more changes.
PR to be closed.

**Pull request closed without merging**
