### PR TITLE
Fix: automatically select default port and remove mojibake

### PR DESCRIPTION
**Pull request by LinjingZhang**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Improve xmc flasher

Related Issue
DESMAKERS3766, DESMAKERS4040

Context
 - If no serial port is selected, pick first jlink device and log the right port 
 - Remove mojibake in uploading log

:no_entry: Synchronizing uploading windows of arduino IDE and the flasher script log as much as possible -> This delay also occurs when using arduino cli. It cannot be improved unless the arduino source code is changed

### CODE REVIEW

**Comment by LinjingZhang** [comment]
It would be nice to be able to compile/upload different operating systems in CICD.
That way I wouldn't need to test manually ❤️

**Comment by LinjingZhang** [comment]
> Works well for me now! One more thing, can you add this message after flashing if the right serial port **was not selected** beforehand: _"Please select port {newSerialport} for using the Serial Monitor or Plotter."_ See also: [DESMAKERS-3992](https://jirard.intra.infineon.com/browse/DESMAKERS-3992), point 6.

Done

**Comment by jaenrig-ifx** [comment]
If no port is selected, I get this output:
image

Is that the expected behavior?
Other than that it all works very nice :)

**Comment by jaenrig-ifx** [comment]
> It would be nice to be able to compile/upload different operating systems in CICD. That way I wouldn't need to test manually ❤️

That should be doable from the github actions workflow or?

**Comment by LinjingZhang** [comment]
> > It would be nice to be able to compile/upload different operating systems in CICD. That way I wouldn't need to test manually ❤️
> 
> That should be doable from the github actions workflow or?

Compiling is fine, but flash is not so easy ...... Though to test xmc-flasher we better be able to flash。
The idea is to run linux in HIL first, windows is usually tested manually, and then once we have a stable HIL we will look at macOS last.

**Comment by LinjingZhang** [comment]
> If no port is selected, I get this output: image
> 
> Is that the expected behavior? Other than that it all works very nice :)


I fix it with new commits 😄

**Review by ederjc — APPROVED** [review]

**Comment by jaenrig-ifx** [comment]
Working now!

**Review by jaenrig-ifx — APPROVED** [review]

**Pull request merged**
