### PR TITLE
Bugfix/issue#266 cmdjlink permission denied

### PR DESCRIPTION
**Pull request by LinjingZhang**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
The download path creates permission problems if the Arduino IDE is installed for all users of Windows. 

Related Issue
https://github.com/Infineon/XMC-for-Arduino/issues/266

Context
Store the intermediate jlink files in temporary folder to solve the permission problem.
This shoud work for all OS - test needed:

- [x] Windows
- [x] Linux

- [x]  MacOS
There were some problem with macOS:
1.  python path. https://forum.arduino.cc/t/esp32-problem-with-compilation-on-macos-12-3-monterey/969771/21
so I changed "python" to "python3". for windows I kept "python"
2. Jlink and java installation for macbook M2 (arm64). I wasted some time on downloading the correct package.

### CODE REVIEW

**Review by OlafFilies — COMMENTED** [review]
Looks Ok

**Review by OlafFilies — APPROVED** [review]

**Comment by ederjc** [comment]
Looks good to me. How did you test it so far?

**Comment by jaenrig-ifx** [comment]
Yep, looks good 👍

**Review by jaenrig-ifx — COMMENTED** [review]
Can we before merge test it in linux and  macos?

**Comment by LinjingZhang** [comment]
@ederjc @jaenrig-ifx 
I will test it on LabPC / macbook, I have asked @OlafFilies for help😄 
This problem is most likely windows-related, but I also would like to test on all os to check I didn't break anything.

**Comment by jaenrig-ifx** [comment]
What is the deal with M2 macbooks?

**Review by jaenrig-ifx — APPROVED** [review]

**Comment by LinjingZhang** [comment]
> What is the deal with M2 macbooks?

I'm just unfamiliar with macbook myself 😿 
Now tested on macOS. It works fine 😸

**Review by jaenrig-ifx — APPROVED** [review]

**Pull request merged**
