### PR TITLE
24 ghz radar

### PR DESCRIPTION
**Pull request by IFX-Anusha**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Compilation errors in the https://github.com/Infineon/XMC-for-Arduino/tree/master/libraries/BGT24LTR11-Pulsed-Doppler-Radar/examples is fixed by this branch

### CODE REVIEW

**Review by jaenrig-ifx — APPROVED** [review]

**Comment by boramonideep** [comment]
All good. However, since the XMC_BOARD parameter is changed in the `pins_arduino.h` file, it should also be changed in the `boards.txt` file to prevent confusion. 

@jaenrig-ifx: Awaiting your comment.

**Comment by jaenrig-ifx** [comment]
@boramonideep Name changed all over the project. The only one not modified was the package_index_infineon.json as this is how it appears in previous versions.

**Review by techpaul — APPROVED** [review]

**Comment by techpaul** [comment]
Looking good have fun with Wiki updates

**Comment by boramonideep** [comment]
> @boramonideep Name changed all over the project. The only one not modified was the package_index_infineon.json as this is how it appears in previous versions.

@IFX-Anusha @jaenrig-ifx  Everything works.

**Comment by jaenrig-ifx** [comment]
XMC4700 only supporting its own built-in library. CI integration reverted.

**Review by boramonideep — APPROVED** [review]

**Pull request merged**
