### PR TITLE
Enable XMC4200 P2GO

### PR DESCRIPTION
**Pull request by boramonideep**
By creating this pull request you agree to the terms in CONTRIBUTING.md.
https://github.com/Infineon/.github/blob/master/CONTRIBUTING.md
--- DO NOT DELETE ANYTHING ABOVE THIS LINE ---

CONTRIBUTING.md also tells you what to expect in the PR process.

Description
Enabling the XMC4200_Platform2GO board in the XMC-for-Arduino BSP. 

Context
Creating a variant and the necessary infrastructure to enable the XMC4200_Platform2GO board into the XMC-for-Arduino repository.

### CODE REVIEW

**Review by jaenrig-ifx — APPROVED** [review]
Pins checked again board manual 👍

**Comment by techpaul** [comment]
Will tweak the LED library example so you don't have to put a dummy LED2 in the pins_arduino.h should be available in a few hours

**Comment by techpaul** [comment]
Awaiting merges but see 
https://github.com/Infineon/XMC-for-Arduino/pull/196/commits/4e9e1a0dc6b7264f1c5547c08bb6260f6ead4e95

LED  Library available that includes XMC4200 Platform 2 Go documentation and example will work with ONE LED

LED.h modified to make sure at  least ONE LED defined
example modified to use one or two LEDs depending on board
Documentation updated to include XMC4200 Platform 2 Go
libraryprperties updated for revision change

Has been test compiled before being made available

**Comment by jaenrig-ifx** [comment]
Thanks @techpaul !
Let us check the PR, but that allows to remove the dummy LED2 👍

**Review by djaumann — APPROVED** [review]

**Comment by djaumann** [comment]
@techpaul Thanks for the contribution, looks very good!

Also no comments from my side  for this PR👍

**Comment by djaumann** [comment]
I also checked the board and it's peripherals. Everything was working without any problems.

**Pull request merged**
