### PR TITLE
Automation release and XMC440 variant

### PR DESCRIPTION
**Pull request by jaenrig-ifx**
* Added release automation with Github actions
* Added support for XMC4400 Platform 2Go

### CODE REVIEW

**Comment by jaenrig-ifx** [comment]
I think we can then release V1.5.0 with all develop changes into master.

**Comment by techpaul** [comment]
Can it wait a few days for one develop pull #143 to have any reviews and be icluded ?

**Comment by jaenrig-ifx** [comment]
Yes, sure. Anyhow I have released from the xmc4400 branch, as we needed it for a project.

**Comment by techpaul** [comment]
With or without develop merged into master as I do not see that BEFORE V1.5.0

**Comment by jaenrig-ifx** [comment]
Hi @techpaul,

I am not sure if I fully get your question.... The tag of the [release V1.5.0 ](https://github.com/Infineon/XMC-for-Arduino/releases/tag/V1.5.0) is from the "xmc4400" branch. The "xmc4400" branch, which was branched from "develop".

The assests repository will no longer host the new releases "package_infineon_index.json" for newer versions. (Just now updated for this version in the [assets repo releases](https://github.com/Infineon/Assets/releases/tag/current).
Now you should be able to upgrade to version 1.5.0 from the board manager of the Arduino IDE.

Some further comments:

From now on the "package...json" url points to the latest release of the xmc-for-arduino repository. (no need to host assets elsewhere). The URL needs to be manually changed in the ide. Noted in the [README](https://github.com/Infineon/XMC-for-Arduino/tree/xmc4400#using-arduino-ide )  
The json manifest and the zipped software release are automatically generated and uploaded to the assets when a new github release is created.
Once merged, (still missing) I have to change the github action yaml to enable the release process from the master branch.

Also by removing the "arm" root folder in the repository (as it is in the master now), we can directly clone the repository into the arduino installation path "<arduino ide installation path>/package/infineon/hardware/arm/x.y.z/", and work directly on it. 
I am not sure how you are doing it, but personally I found no other cleaner way without copy/paste operations and leverage proper git usage.

**Comment by techpaul** [comment]
If you compare branches, releasing xmc4400 branch ahead of merging develop into master is leaving disparity

You probably should have merged UP TO date develop into master first then merged newer xmc4400 as comparing branches shows differences.

This appears to have been done hastily using an older version of develop as the base

**Comment by techpaul** [comment]
Cloming or downloading zip files of a repository (and/or branch) is possible direct from code section of the repository.

Whilst removing arm root folder has benefits you have created a release which is newest version available to ALL users from IDE, that in NO way matches master branch This in my opinion as a release has been done for benefit of ONE supported board and lost any benefits elsewhere, potentially causing support issues.

You have created a potential versioning issue as the version of develop you used as a base was out of date,(the list above on;y contains differences of what is newer in xmc4400, not what is newer in develop to xmc4400, so we will now have issues with

- Getting master branch to match release
- merging develop into master
- ensuring xmc4400 and new build files included and reference for release be ONLY master branch.
- Personally develop should be made available as Beta weekly build (just like Arduuino do themselves)

You have NOT removed ALL reliance on assets repository as parts of that should be merged with this repository with suiltable ignore in release, the Wiki and other places rely on this for the pinout diagrams and the source files.

My view is the release and repositories should contain a Documentation folder for pin out diagram JPGs and the source file of the SVGs, (source files not included in release), reference these locations from the wiki.

**Comment by jaenrig-ifx** [comment]
> Cloming or downloading zip files of a repository (and/or branch) is possible direct from code section of the repository.
> 
True.
> Whilst removing arm root folder has benefits you have created a release which is newest version available to ALL users from IDE, that in NO way matches master branch This in my opinion as a release has been done for benefit of ONE supported board and lost any benefits elsewhere, potentially causing support issues.
> 
You can clone and download the zip. But you cannot work directly with the repository cloned in the installation path. 
This change I will keep unless there is an alternative for a clean way to work with the repository local working copy itself and the Arduino IDE.
The repository and the created zipped release do not need to match one to one the content.
That should not affect the other versions (that is the intention) once updated the json package file url link.

> You have created a potential versioning issue as the version of develop you used as a base was out of date,(the list above on;y contains differences of what is newer in xmc4400, not what is newer in develop to xmc4400, so we will now have issues with
> 
> * Getting master branch to match release
> * merging develop into master
> * ensuring xmc4400 and new build files included and reference for release be ONLY master branch.
> * Personally develop should be made available as Beta weekly build (just like Arduuino do themselves)
> 

The reasons to do this were:
- I needed to check the release automation (that could have been done somewhere else in a fork, before all the mess of tests release I had created. Sorry, I know... )
- There is a event for which this particular variant needed to be checked by other users not into xmc-for-arduino development and maintenance. So they needed to have it accessible from the board manager.

So as, many other inappropriate test releases were done, this can be deleted, and release from master. **So yes, agree**. Lets not waste more discussion and git flow explanations, and keep as good practice reference the git flow branching model as you describe. Again, sorry, for such a sacrilege ;) 

> You have NOT removed ALL reliance on assets repository as parts of that should be merged with this repository with suiltable ignore in release, the Wiki and other places rely on this for the pinout diagrams and the source files.
> 

I hope so regarding code assets (and tools), and Arduino IDE required metadata.
Not regarding images. 

> My view is the release and repositories should contain a Documentation folder for pin out diagram JPGs and the source file of the SVGs, (source files not included in release), reference these locations from the wiki.

Agree. But not yet done. Nevertheless, the wiki is another repository.
And actually another alternatives to avoid large binaries in the code repo (I guess that would be one of the reasons to have this "assets repo") is to keep all the sources in that repository. The wiki will only show the markdown files. If you clone wiki repo you can get all those .svg, images, and etc.

**Comment by techpaul** [comment]
@mhollfelder @jaenrig-ifx 

Having spent a lot of time sorting things out from past obvious marketing led **event** releases and getting examples better structured. My comments are this, bearing in mind I have many **DECADES** experience of dealing with such messes

1/ After the event Emdedded World or whatever it is the **DELETE** release V1.5.0
2/ You sort out integration of the branches correctly
3/ Release a V1.5.x (or many small step versions) that has **ALL** fixes from develop into master **THEN** any automation and restructuring that has been done to supposedly make things easier for lazy people.

I am seriously considering withdrawing any contribution efforts as this repository is obviously meant to be only a **MARKETING** quick and very dirty demo, please don't look at the source just look at the pretty pictures demos.

I do understand about making things for events, as ONE example of many  in 1983 in 4.5 months I went from blank piece of paper to fully designed multi-processor control sysytem designing the hardware, software and some of the mechanical parts for large racks of TV studio equipment to be shown at International TV show in Swiitzerland. All using 8 bit processors and writing in assembler.

Over the years I have done many projects that have had short time periods in many languages, processors and hardware  designing and building all parts, some cases 2 months delivering two different small systems in parallel on my own.

This should have been done as at least 3 separate staged releases incorporating other fixes and keeping versioning **SANE**, what you do for internal test branches does not matter until you release them and potentially make existing customers/users support difficult with messes on releases

**Comment by techpaul** [comment]
One further point you claim

"Release is tagged with XMC4400"

This is WRONG it is tagged with Version number NOT the branch it is from

**Comment by jaenrig-ifx** [comment]
Dear @techpaul ,

I highly appreciate your commitment and contribution to this project, and I believe I can talk for the rest of the Infineon. And I highly respect the work you and the rest of the contributors have done here. I try to build on top of that. 

From the part I am responsible of, I apologize if the project is not currently meeting your expectations. I might even agree with many of your statements. 

Said that, I insist on keeping these forums and chats as constructive technical discussions to resolve the issues that bring us here, rather that on ad hominem argumentation.
   
So, as this specific pull request has technically nothing to do with the release, it is just a branch intented to be merged into develop, I would say we keep the review at this level.
From that point of view, I see no futher comments.

The release topic is already clear. It will be removed as soon as this branch has made it into master.

**Pull request merged**
