### PR TITLE
fixed and improved parameter handling 

### PR DESCRIPTION
**Pull request by mkiessling-ifx**
I reworked the branch a bit, to improve it and adding some features.
- I removed the "arm" lib from previous commit, so only cortex-m4 variant is available

Further I 
* improved parameter handling and Fixed setting parameter
* Added example to change parameters
* Provide option to set output device

### CODE REVIEW

**Comment by techpaul** [comment]
CORTEX-M4 IS NOT VALID !!!!!!!!!

**Comment by techpaul** [comment]
Please PULL latest develop branch and merge your changes LOCALLY into that and test again.

So many things are wrong

**Comment by mkiessling-ifx** [comment]
> CORTEX-M4 IS NOT VALID !!!!!!!!!

Thank you for being really concreate NOW! 

let me rework that!

**Comment by mkiessling-ifx** [comment]
> So MANY things wrong
> Total misunderstanding of how things work from the Arduino IDE and folder structure

@techpaul: sorry the mistake was, that I did not sync'ed with latest develop-branch yesterday! Since there the metadata was already fixed, I missed that. Since it seems to be the simplest way (for me) to delete the folk and re-fork freshly.
The changes in new upcoming pull-request are small, only related the my lib and hope they are o.k. now to be approved. 
I did not found good examples on how to setup lib only builds, so I failed on that. 
Honestly some things on Arduino setup are NOT very intuitive (to me) and in a flow. But I think we find good solution in the end. Thank you for you contribution and you patience. 
There is one more thing that is not clear: How can I restrict the use of the lib to the XMC4700 Radar Baseboard only? Since the lib is due to internal use of dedicated HW peripheral and HW dependencies not very portable.

**Comment by mkiessling-ifx** [comment]
deleted old fork and re-forked again with freshly sync'ed development branch, to raise fresh pull-request.

**Comment by techpaul** [comment]
mkiessling-ifx

It is very simple when the following files are PROPERLY configured.

_boards.txt_
_package.txt_

When a build occurs the board variant being made for is defined on the compiling recipe command line as

-DXMC4700_Radar_Baseboard

from recipe.c etc  in _platform.txt_
~~~
    .....  -D{build.board_variant} ....
~~~
Which comes from _board.txt_
~~~
XMC4700_Radar_Baseboard.build.board_variant=XMC4700_Radar_Baseboard
~~~
Which is **different** from the name used everywhere else
~~~
XMC4700_Radar_Baseboard.name=DEMO Radar BB XMC4700
~~~
As the file does not match up correctly

So in your library HEADER file as early piece of code (after includes) you state

~~~
#if not defined XMC4700_Radar_Baseboard
#error  "Pulsed Radar is NOT supported on this board"
#endif 
~~~

This will cause compilation to stop for WRONG board

**Pull request closed without merging**
