### PR TITLE
Preparing Release V1.1.0

### PR DESCRIPTION
**Pull request by mhollfelder**
Originally, we wanted to release V1.0.6 as the next release. 
However, due to the latest feedback and improvements, we decided to prepare a release for V1.1.0 with major changes.

As techpaul has committed lots of changes and improvements, I decided to create a 'release' branch and merge the pull requests as well as other changes step by step from the develop as well as xmclib branch.

I opened this pull request to prepare the next steps for finalizing a RC.
Follow up with the changes will follow.

Best,

Manuel

### CODE REVIEW

**Comment by techpaul** [comment]
I assume this is to do a RC using XMCLIB V2.1.8, for now, Not an issue for me at present

**Comment by techpaul** [comment]
Most of the fconflcts are size of change area, Interesting merge gave wiring_time.h to have
repeated 

    /* SysTick counter */
    extern volatile uint32_t g_systick_count;

**Comment by mhollfelder** [comment]
Currently, all changes have now been merged into develop and branch should be clean for merge into release.
I need to do some more sanity checks as well as document the changes properly, but I am expecting a release by tomorrow or the day after tomorrow.

Best regards,

Manuel

**Comment by techpaul** [comment]
Before release you might want to check wiring_time.h

Lines 117 and 118 can be deleted (repeat of previous lines) as mentioned before

**Comment by mhollfelder** [comment]
I have deleted it, thank you very much.

I need to do two more tests before I can release the new version and I am currently waiting for the hardware.
Therefore, I might not be able to release it today, unfortunately.
When I am done, I will merge develop into release as well as release the new version quickly.

Best regards,

Manuel

**Pull request merged**
