### PR TITLE
Inital Commit XMC4500 Relax Kit

### PR DESCRIPTION
**Pull request by nmaas87**
This should enable inital XMC4500 Relax Kit support - however, the pins_arduino.h is no yet complete and needs to be reworked before merging (But getting blinking LED1 and LED2 by using pin 3 and 2 already works ;)).

### CODE REVIEW

**Comment by nmaas87** [comment]
There is still missing a ton of stuff, i.e. correct labeling of PWM pins, support for I2C / SPI in the Librarys and such - however, for most basic stuff it should work and I hope it could be a useful starting point for a more  correct implementation of the XMC4500 Relax Kit.

**Comment by Infineon** [comment]
This is really great, thank you very much for your efforts as well as contribution to the XMC-for-Arduino initiative! 
Currently, we are busy with the embedded world, but we will create a branch for further development of the XMC4500 series as well as integration in the Arduino IDE to support your development :)

Best regards,

The Infineon Team

**Comment by Infineon** [comment]
Just a short question: how was your approach towards integration into the Arduino IDE as we do not have a VCOM with the on-board debugger. Did you use an external debugger or omitted the COM port? Or is there a problem which we are not aware of?

**Comment by nmaas87** [comment]
Thanks a lot for working on that :)!
I made the lazy approach as I only modified AVR board files to this point in time and my ARM (especially CMSIS) knowledge is very limited (sadly). So I just took the needed files (as seen in my PR) from the Infineon Board Package for Keil and adapted the XMC4700 files from this Github project to match it. After that, I took the XMC4500 CPU manuals and XMC4500 Relax Kit manuals and tried to improvise on the https://github.com/Infineon/XMC-for-Arduino/blob/master/arm/variants/XMC4700/config/XMC4700_Relax_Kit/pins_arduino.h - to get something working out of it. However, I had no debugger or serial interface for doing that and I could not get serial working. I am fairly sure that the Keil Examples for the XMC4500 will hold some idea of how to get it working, but sadly I did not have the time to look into that :(.

**Comment by mhollfelder** [comment]
We finally decided not to integrate the XMC4500 right now as the missing VCOM makes an Arduino integration hardly possible right now. 
I hope you understand this :)

We will keep this pull request in mind and see whether we will find a workaround or not.
Sorry for that!

Best regards,

Manuel

**Pull request closed without merging**
